config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'best_seats', to: 'home#best_seats'
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :summary, :year, :genre, presence: true
  validates_uniqueness_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @seats = params['seats']
    @available_seats = params['available_seats']

    if valid_seats(@seats) && valid_available_seats(@available_seats)
      @result = BestSeatsPresenter.new(@seats, @available_seats).best_seats
      flash.clear
    elsif @seats || @available_seats
      flash[:notice] = "Not valid inputs for number of seats and available seats."
    else
      flash.clear
    end
  end

  private
  
  def valid_seats(seats)
    seats.present? && seats == seats.to_i.to_s
  end

  def valid_available_seats(available_seats)
    json = JSON.parse(available_seats) rescue nil
    available_seats.present? && json && json['venue'] && json['seats']
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  def index
    @movies = Movie.all
  end

  def show
  end
  
  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:notice] = 'Movie was successfully created.'
      redirect_to @movie
    else
      flash[:notice] = 'There was a problem creating the movie.'
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      flash[:notice] = 'Movie was successfully updated.'
      redirect_to @movie
    else
      flash[:notice] = 'There was a problem updating the movie.'
      render :edit
    end
  end
  
  def destroy
    @movie.destroy
    flash[:notice] = 'Movie was successfully deleted.'
    redirect_to movies_url
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
  
  def movie_params
    params.require(:movie).permit(:title, :summary, :year, :genre, :imdb_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.erb
<div id="page-container">
  <div id="header">
    <h1>Best Available Seats</h1>
    <button><%= link_to "Movie Catalog", movies_path %></button>    
    <form>
      <p>
        <label>How many seats do you need?</label>
        <input name="seats" value="<%= @seats %>" placeholder="Number of Seats"></input>
      </p>
      <p>
        <textarea name="available_seats" value="<%= @available_seats %>" placeholder="Available Seats JSON" rows="15" cols="30"><%= @available_seats %></textarea>
      </p>
      <button>Find Best Seats</button>
    </form>
    <p>
      <div class="errors"><%= flash[:notice] %></div>
    </p>
  </div>
  <p id="result"><%= @result %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Best Available Seats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, html: {class: 'form-horizontal'}) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :summary, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :summary, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :year, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :year, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :genre, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :genre, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :imdb_link, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :imdb_link, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<p></p>

app/views/movies/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>Movie Catalog</h1>

<button><%= link_to 'Best Available Seats', root_url %></button>
<button><%= link_to 'Add Movie', new_movie_path %></button>

<ul>
  <% @movies.each do |movie| %>
  <li>
    <p>Title: <%= movie.title %></p>
    <p>Summary: <%= movie.summary %></p>
    <button><%= link_to 'Show', movie %></button>
    <button><%= link_to 'Edit', edit_movie_path(movie) %></button>
    <button><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<ul>
  <li>Title: <%= @movie.title %></li>
  <li>Summary: <%= @movie.summary %></li>
  <li>Year: <%= @movie.year %></li>
  <li>Genre: <%= @movie.genre %></li>
  <li><%= @movie.imdb_link.present? ? link_to('IMDb Link', @movie.imdb_link, target: '_blank') : '' %></li>
  <p>
    <%= link_to 'Edit', edit_movie_path(@movie) %> |
    <%= link_to 'Back', movies_path %>
  </p>
</ul>